### ISSUE TITLE
[Request] Unified common assets storage

### ISSUE THREAD

**Issue by rauanmaemirov** [cartalyst/assetic-filters#2]
Currently I have to either duplicate every library or asset both in admin and frontend themes, or mess with kind of "../../../../admin/default/assets" style injections.
Same thing goes if I want to store all my external lib assets in public folder.

I already discussed this in IRC, and my suggestion was rejected back then.
But since you guys heading in the direction of pluggable themes, this could be the right moment to pitch the idea. :)

I would suggest looking into bower or [component-installer](http://robloach.github.io/component-installer/) (though I don't like their approach with picking component files by hand).

**Comment by brunogaspar** [comment]
I kinda agree, but this requires quite a discussion so we can have a better system in place when it comes to assets, views etc..

I have a few ideas to improve this, but with all certainty this will only be changed/revised once we start to tinker the next major release of Platform.
